influxdata/influxdb-client-go

write.go
Closes #5
This PR fixes an issue where unknown error status codes would return no error.
=> fix(write): returns correct error from unknown status codes

writer.go, writer_test.go
=> fix: fixes possible panic

.circleci/config.yml, generated/tostring.go, internal/scripts/buildclient.go
=> check go fmt on ci

writer.go
=> fix issue #35

writer/writer.go, writer/writer_test.go
Cut a new v0.1.2 release containing the fix to bucket and org argument order.
=> Release v0.1.2

query.go
When the bytes of the response are larger than a certain size, the api will respond to `Content-Encoding: gzip`, so `gzip.NewReader` should be used when` Accept-Encoding` is `gzip`.
```
However, if the user explicitly requested gzip it is not automatically uncompressed.
```
=> Fix query: transport when gzip

README.md
Now the example has some more color!
=> Fix syntax in the example

README.md, e2e_test.go, query.go, writer/options.go, writer/writer.go, writer/writer_test.go
Features:
- (https://github.com/influxdata/influxdb-client-go/pull/61) Support for `writers.WithContext()` used to inject a `context.Context` on buffer flushes.
Bug Fixes:
- (https://github.com/influxdata/influxdb-client-go/pull/56) QueryCSV now respects `Content-Encoding=gzip` and handle appropriately.
Testing:
- (https://github.com/influxdata/influxdb-client-go/pull/61) Improvement to query made during e2e test.
Documentation:
- (https://github.com/influxdata/influxdb-client-go/pull/62) GH code highlighting in docs
=> Release v0.1.3

write.go
We have a use case where manipulating the information we have to shape
them as influxdb.Metric is very expensive. We already have the line
protocol for them.
This change allow us to pass the line protocol directly to the Write
function without having to do any extra manipulation.
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>
Co-Authored-by: Chris Goller  <goller@gmail.com>
=> feat: make write request public

README.md
Updated examples to contain client.Close()
=> docs: All examples contains client.Close()

README.md
- Fixing #85 by adding the Documentation section to readme
- Added TOC
- Grammar fixes
=> docs: fixing #85 and adding other readme improvements

api/buckets.go, client_e2e_test.go, domain/client.gen.go, domain/swagger.yml, domain/types.gen.go
Sync with the latest InfluxDb 2 swagger.yml
=> chore: sync with the latest influxdb 2 swagger.yml

api/http/options.go, client.go, options.go
Removing remaining deprecated methods. Continuation of #173
=> chore(APIs): removing remaining deprecated methods

api/buckets.go, api/buckets_e2e_test.go, api/delete_e2e_test.go, api/labels.go, api/organizations.go, api/organizations_e2e_test.go, api/paging.go, api/paging_test.go, domain/client.gen.go, domain/swagger.yml, domain/templates/client-with-responses.tmpl, domain/types.gen.go, internal/write/service_test.go, scripts/influxdb-restart.sh
Synced with Rc0 swagger: 
- added orgs Get* pagination
- added support for After
- disabled delete tests
- other fixes
=> chore(swagger): syncing with the rc0 swagger

README.md, TODO.md, go.mod, go.sum, inluxclient/client.go, inluxclient/client_test.go
Adding initial implementation for Params and Client with New.
Package docs is still subject to further updates
=> feat(v3): Params, Client and New

CHANGELOG.md, README.md
=> fix: Readme.md formatting

CHANGELOG.md, api/http/options.go, api/http/service.go
=> feat: allow Doer interface for http.Service

CHANGELOG.md, api/http/options.go, api/query.go
Closes #258 
Reading remaining data in `QueryTableResult.Close()`.
=> fix: Leaking connections 

CHANGELOG.md, README.md
Documentation (Readme) enhanced about HTTP proxy configuration and redirect description.
=> docs: documenting HTTP proxy and redirects

CHANGELOG.md, domain/client.gen.go, domain/oss.yml, domain/types.gen.go
Synced generated server API with the latest [oss.yml](https://github.com/influxdata/openapi/blob/master/contracts/oss.yml).
=> chore: synced with the latest oss.yml

.circleci/config.yml
Use the recommended Ubuntu image. Related to [Ubuntu 14.04 machine image deprecation & EOL](https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/).
=> chore(ci): use recommended ubuntu image

.circleci/config.yml, CHANGELOG.md, Makefile
Added makefile for simplifying testing from the command line. It is used in the CircleCI script
=> test: Adding makefile for simplifying testing

CHANGELOG.md, domain/client.gen.go, domain/templates/imports.tmpl, go.mod, go.sum
Upgrade of the lib gopkg.in/yaml from v2 to v3
=> chore: upgrade gopkg.in/yaml to v3

CHANGELOG.md, README.md
- Added GOPATH installation description
- Added error handling to Basic Example.
=> docs: Readme improvements

api/writeAPIBlocking.go
=> docs: fix type in writeAPIBlocking.go
