README.md
Closes #10 
This PR updates the readme to clarify to the reader that this client only works for the 2.x line, and includes a link to the 1.x client library.
=> chore(readme): update readme to direct readers to 1.x client

README.md
fix readme to point out you need go1.12 to build the library.
closes #11
=> chore: fix readme to point out you need go1.12 to build

writer.go
Since method has an early exit, we should defer the wait group decrement.
closes #30
=> fix: defer waitgroup decrement

query.go
Indents the code for the godoc so that it displays properly.
=> doc: Fix code block for QueryCSVResult.Next()

query.go
if resp is nil, it will panic, because err is not nil, will exec the defer function before return.
=> fix: query csv panic

client.go, errors.go, query.go, write.go, write_test.go, writer/doc.go, writer/options.go, writer/retry.go, writer/retry_test.go, writer/support_test.go, writer/writer.go, writer/writer_test.go
closes #46
This reinstates the ability to automatically retry writes based on known transient error conditions.
See updates to docs.go:
```go
import (
"time"
"github.com/influxdata/influxdb-client-go"
"github.com/influxdata/influxdb-client-go/writer"
)
func main() {
var (
cli, _ = influxdb.New("http://localhost:9999", "some-token")
bucket = "default"
org    = "influx"
)
// construct a writer with 3 maximum attempts per call to Write and linear backoff derived from number of attempts
// i.e. a first attempt is followed by a 1 second delay before the second attempt
// a second attempt is followed by a 2 second delay before the third attempt
var (
retryOpts = []writer.RetryOption{writer.WithMaxAttempts(3), writer.WithBackoff(writer.LinearBackoff(time.Second))}
wr        = writer.New(cli, …
```
=> writer.RetryWriter implementation

writer/point.go, writer/point_test.go
This ensures that flush is called on `*writer.PointWriter.Close()`.
Prior to this change a Close with a partially filled buffer would get discarded and lost.
=> Ensure flush is called on PointsWriter.Close

writer/writer.go, writer/writer_test.go
The order of the bucket and organization arguments is incorrect. The client takes a bucket before the org. Sadly my test was ensuring it was the wrong way around.
This reorders the arguments correctly.
=> Reorder arguments bucket and org in bucket writer

e2e_test.go
This gets rid of the annoying error in the flux grouping.  It doesn't really affect the test, but is better regardless.
=> better e2e test

writer/options.go, writer/writer.go
This allows the threading of a `context.Context` to be made for all batches written to a `writer.PointWriter` constructed with `New(...)`
Each time `BufferedWriter.Flush` is called this `context.Context` will be used in the call to `client.Write(ctx, ...)`.
=> Add WithContext config option to writers package

write.go, write_test.go
I recently learned `UintSupport` is required for 2.x and not supported in 1.x.
This is causing some bugs when writing uint64 values with this client.
This change enabled `UintSupport` in the line protocol encoder used in client writes.
=> Ensure UintSupport enabled in line-protocol encoder on write

e2e_test.go, errors.go, write.go, write_test.go, writer/options.go, writer/retry.go, writer/retry_test.go, writer/support_test.go
This changes the retry writer to split excessively large payloads when
the influxdb returns an http.StatusRequestEntityTooLarge response.
Closes: https://github.com/influxdata/influxdb-client-go/issues/72
=> feat: Retry writer should split too-big payloads

doc.go
With this commit, "go doc" will display an example usage.
=> doc(doc.go): add example usage to go documentation

README.md
As go uses tab as indent chars it becomes misformatted when placed in markdown. This PR fixes forgotten formatting changes - issue #89
=> fix: Fixing #89 - fixed examples indentation

CHANGELOG.md, api/authorizations.go, api/doc.go, api/organizations.go, api/users.go, domain/utils.go, examples_test.go, internal/http/service.go, internal/http/userAgent.go
=> docs: Added API doc examples

CHANGELOG.md, client.go, query.go, setup.go, write.go, writeApiBlocking.go, writeService.go, write_test.go
Renamed `InfluxDBClient` interface to `Client`, so the full name `influxdb2.Client` suits better to Go naming conventions
Closes #103
=> refactor: Renaming InfluxDBClient -> Client

write.go
This extends the documentation on this method to clarify a couple of major caveats that users need to be aware of.
=> Additional documentation on WriteApi.Errors()

CHANGELOG.md, query.go, query_test.go, table.go
Closes #110
Added handling of empty (nil) values in the flux result set
=> fix: Handling empty values 

CHANGELOG.md, README.md
Closes #109
Adding a description and example of using client with InfluxDB 1.8+.
=> docs: Clarify how to use InfluxDB 1.8+ with client

CHANGELOG.md, options.go
Closes #108
Fixing default retry interval value in the comment for the retry interval
=> fix: Fixing comment for retry interval (#108)

CHANGELOG.md, README.md, examples_test.go
Closes #102 
Added docs and examples for WriteApi.Errors usage into the Readme and API docs
=> docs: Doc and examples for WriteApi.Errors()

CHANGELOG.md, api/delete.go, client.go, client_e2e_test.go
Closes #117 
Add Delete API for allowing deletion of time series from buckets
=> feat: Added Delete API for deleting data from bucket

CHANGELOG.md, README.md, api/examples_test.go, api/labels.go, api/organizations.go, client.go, client_e2e_test.go, domain/client.gen.go, domain/swagger.yml, domain/types.gen.go, go.mod, internal/examples/fakeclient.go
Closes #130
Added support for managing labels in general and managing labels in organization
=> feat: Labels API

CHANGELOG.md, api/query.go, api/query/table.go, api/query_test.go, client_e2e_test.go
Closes #133, fixes problem in #110 and #123
Allowing reordering of annotations in a flux query result.
=> fix: allow reordering of annotations in flux query result

CHANGELOG.md, api/write/options.go, api/write/options_test.go, api/write_test.go, internal/write/service.go, internal/write/service_test.go, options.go, options_test.go
Closes #135
Added possibility set default tags
=> feat: adding possibility to set default tags

CHANGELOG.md, api/write/ext.go, api/write/point_test.go
Related to https://github.com/influxdata/influxdb-client-java/issues/127
=> fix: serialization of `\n`, `\r` and `\t` to Line Protocol

CHANGELOG.md, client_test.go, internal/http/error.go, internal/http/service.go
This PR fixes errors from InfluxDB 1.8 being empty. It does this by falling back to reading the `X-Influxdb-Error`, and if that doesn't work, then `http.Error` would return the unexpected status code inside the error message.
Before PR:
After PR:
=> fix: errors from InfluxDB 1.8 being empty

api/write/ext.go, api/write/point_test.go
=> fix: `=` is valid sign for measurement name

client_e2e_test.go
Beta 13 introduced issues [#18773](https://github.com/influxdata/influxdb/issues/18773) and [#18653](https://github.com/influxdata/influxdb/issues/18563) that 
were fixed in beta 14 (without a notice). Updating test to reflect that.
=> chore: Adjusting Label API tests after fixes

CHANGELOG.md, client.go, client_test.go, internal/http/service.go
Closes #149
Properly concatenating URL path to the final API endpoint
=> fix: Allow connecting to a server on a URL path (#149)

CHANGELOG.md, api/buckets.go, api/organizations.go, client_e2e_test.go
Closes #151
Properly validating returned collection that contains items. It was expected that the server always returns an error instead of returning an empty result set, as it does in other cases
=> fix: Avoiding panic in Find*ByName methods

CHANGELOG.md, api/write.go, internal/write/service.go
Closes #145
- make signalling channels of type struct
- use closing of signalling channels instead of sending messages
=> fix: use idiomatic go style for write channels

.circleci/config.yml
Closes #141
Added mechanism for the tests run that allows creating JUnit output and displaying tests results in the CircleCI Tests tab
=> ci: Adding tests result to the CircleCI Tests tab

.circleci/config.yml, api/authorizations_e2e_test.go, api/buckets_e2e_test.go, api/delete_e2e_test.go, api/labels_e2e_test.go, api/organizations_e2e_test.go, api/users_e2e_test.go, client.go, client_e2e_deprecated_test.go, client_e2e_test.go, scripts/influxdb-restart.sh
Split huge E2E test set in `client_e2e_tests.go` to test/file per tested feature. Except for Setup, Ready, Health, Write, and Query.
=> test(e2e): E2E tests split

CHANGELOG.md, api/http/options.go, api/http/options_test.go, internal/http/service.go, options.go, options_test.go
This allows overriding the http.Client for the http service. If the
client is overridden, the other options are ignored. This allows further
customization such as modifying the underlying http.Transport or the
`CheckRedirect` function.
=> feat: allow overriding the http.Client for the http service

.circleci/config.yml, .github/semantic.yml, api/authorizations.go, api/authorizations_e2e_test.go, api/buckets.go, api/buckets_e2e_test.go, api/delete_e2e_test.go, api/labels_e2e_test.go, api/organizations_e2e_test.go, api/paging_test.go, api/users_e2e_test.go, client_e2e_test.go, scripts/influxdb-restart.sh, scripts/influxdb.conf
- Increased test coverage of management APIs via extending E2E tests
- Added E2E testing of InfluxDB 1.8.1 forward compatibility APIs
=> test(e2e): increase management API coverage via E2E tests

CHANGELOG.md, api/buckets.go, api/buckets_e2e_test.go, api/examples_test.go, api/labels_e2e_test.go, api/organizations.go, api/organizations_deprecated.go, api/organizations_e2e_test.go, client.go, client_e2e_deprecated_test.go, domain/client.gen.go, domain/swagger.yml, domain/types.gen.go
Synced with the latest (beta 16) swagger.  Notably, removed orgs labels API cause it has been removed from the server API
=> chore(API): Sync with the beta 16 swagger

CHANGELOG.md, api/write.go, client.go, client_test.go
Closes #163 
Keeping a single instance of WriteAPI and WriteAPIBlocking for each org and bucket pair.
=> fix:  WriteAPIs management

CHANGELOG.md, api/write/options.go, api/write/options_test.go, api/writeAPIBlocking_test.go, api/write_test.go, internal/test/http_service.go, internal/write/queue.go, internal/write/queue_test.go, internal/write/service.go, internal/write/service_test.go, options.go, options_test.go
- Added exponential backoff
- Added MaxRetryInterval to set maximum retry delay
- Various retry logic fixes
- Added more tests
=> feat: Unifying retry strategy among InfluxDB 2 clients

CHANGELOG.md, api/query.go, api/write.go, api/write_test.go, client.go, internal/http/service.go, internal/log/logger.go, internal/log/logger_test.go, internal/write/service.go, log/logger.go, log/logger_test.go, options.go
Closes #104, closes #144 
- Added Logger interface to enable overriding of the global logger.
- It is also possible to disable logging completely
=> feat: Adding public logging API

CHANGELOG.md, README.md, api/examples_test.go, client.go, examples_test.go
Closes #182
Adding clarification that server URL needs to be base URL to client API docs and all examples in Readme and API docs
=> docs: Adding clarification that server URL needs to be base URL

CHANGELOG.md, api/query.go, api/query_test.go
fix [bug](https://github.com/influxdata/influxdb-client-go/issues/190): failed to parse boolean datatype in `QueryTableResult`.
=> fix: boolDatatype not match line protocol

CHANGELOG.md, api/http/options.go, api/http/options_test.go, client.go
Closes #183 
Client.Close() also closes idle connections if the HTTP client was created internally  (#183)
=> fix: Client.Close() also closes idle connections 

CHANGELOG.md, api/examples_test.go, api/http/options.go, api/http/service.go, api/users.go, api/users_e2e_test.go, client.go, examples_test.go, go.mod, options.go
Closes #45
Allowing a user to authenticate via username and password. Available via explicit calls to UsersAPI.SignIn() and UsersAPI.SignOut()
=> feat: Added SignIn and SignOut

.circleci/config.yml, CHANGELOG.md, README.md, api/authorizations_e2e_test.go, api/buckets_e2e_test.go, api/examples_test.go, api/http/service.go, api/http/service_test.go, api/users_e2e_test.go, client.go, client_e2e_test.go, client_test.go, examples_test.go, internal/write/service_test.go, scripts/influxdb-restart.sh
Closes #195
Changing server port 9999 -> 8086 in examples and docs.
=> feat: Changing server port 9999 -> 8086

CHANGELOG.md, README.md
avoid 
```field type conflict: input field "max" on measurement "stat" is type float, already exists as type integer dropped=1``` 
error
Update example in README.md
=> feat: Unify type of max field in example

CHANGELOG.md, api/writeAPIBlocking.go, api/writeAPIBlocking_test.go
Closes #208
Synchronizing access to the `write.Service` in the `WriteAPIBlocking.write` function to prevent race conditions.
=> fix: synchronizing access to write service

api/write.go
Closes #
Write the point encoding err to the errCh when the errCh is not nil.
=> fix: write to errCh when point encoding fails

api/delete_e2e_test.go
Enabled e2e test after update InfluxDB to `2.0.3`.
=> chore: enabled e2e test

README.md
=> docs: fix invalid links.

CHANGELOG.md, README.md
- Change links leading to sources to go to API docs
- Fixed broken links to InfluxDB docs
=> docs: Changed remaining links to sources to API docs

CHANGELOG.md, api/http/service.go, api/query_test.go, api/tasks_e2e_test.go, api/write.go, api/writeAPIBlocking_test.go, api/write_test.go, client_test.go, internal/write/service.go, internal/write/service_test.go, options_test.go
Closes #226 
Retry write also on network errors
=> fix: Retry also on network errors

LICENSE, TODO.md, annotatedcsv/reader.go, annotatedcsv/reader_test.go, inluxclient/client_test.go, inluxclient/query.go, inluxclient/query_test.go, internal/csv/reader.go, internal/csv/reader_test.go
Rework of #230.
First PR for query: Adding `annotatedcsv.Reader` imported from https://github.com/rogpeppe/annotatedcsv and edited.
Update 3/1: Based on suggestions, added `QueryResultReader` to keep `annotatedcsv.Reader` as general as possible and move some features here:
- treating error definition in section as a Go error
- `NextRow` advances to the first row of the first section
=> feat(v3): Query part I. - annotatedscv/reader

internal/write/service.go, internal/write/service_test.go
Closes #236 
When a write error occurs, explicitly test for `MaxRetries()` being zero, and do not proceed with retry logic if this is the case.
=> fix: don't attempt retries if MaxRetries is set to zero

CHANGELOG.md, api/delete_e2e_test.go, api/http/error.go, api/users_e2e_test.go, api/write/options.go, api/writeAPIBlocking.go, api/writeAPIBlocking_test.go, api/write_test.go, client_e2e_test.go, client_test.go, internal/test/generators.go, internal/write/service.go, internal/write/service_test.go, options.go
Closes #235
Blocking write client doesn't use retry handling.
=> fix: Removing retrying from blocking write

CHANGELOG.md, client.go, client_e2e_test.go, domain/swagger.yml, domain/types.gen.go
Types and API client is generated from the latest InfluxDB swagger.
Most notable changes:
-  Setup (onboarding) now sends correctly retentionDuration, if specified. 
- `RetentionRule` used in `Bucket` now contains `ShardGroupDurationSeconds` to specify shard group duration (available in the next InfluxDB 2 release, not in current v2.0.4)
=> chore: synced with the latest swagger

CHANGELOG.md, README.md, api/write.go, api/writeAPIBlocking.go, client.go, examples_test.go
- [Custom server API example](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2#example-Client-CustomServerAPICall) now shows how to create DBRP mapping
- Improved documentation about concurrency
=> docs: example and API docs improvements

CHANGELOG.md, api/query/table.go, api/query/table_test.go
Closes #246
Reliably reading values from the map.
=> fix: reliably retrieving values (#246)

.circleci/config.yml, CHANGELOG.md, api/buckets.go, api/query.go, internal/log/logger.go, internal/log/logger_test.go, internal/write/service.go, internal/write/service_test.go, log/logger.go, log/logger_test.go
Closes #244, closes #245 
- Conditional debug logging of buffers.
- Speeding up slow write tests.
- Package `log` added to the coverage report
=> fix: conditional debug logging of buffers

README.md, TODO.md, annotatedcsv/decode.go, annotatedcsv/decode_test.go, annotatedcsv/reader.go, annotatedcsv/reader_test.go, inluxclient/query.go, inluxclient/query_test.go, internal/reflect/visiblefields.go, internal/reflect/visiblefields_test.go
- Added `Reader.Decode(x interface{}) errror` to convert CSV values to a struct fields or a slice
- `Reader.NextRow()` doesn't convert values 
- `Reader.Row()` returns raw CSV data
=> feat(Query): Adding Reader.Decode

CHANGELOG.md, README.md
Update Line Protocol document link to v2.0 to meet the target version (InfluxDB 2.x) of this repo.
Also markdown-to-HTML rendering in the old v1.6 document is broken.
=> docs: update Line Protocol document link to v2.0

CHANGELOG.md, api/write.go, api/write/options.go, api/write/options_test.go, api/writeAPIBlocking.go, internal/write/service.go, internal/write/service_test.go, options.go, options_test.go
This PR aligns retry strategy implementations across all official InfluxDB client libraries so that a delay for the next retry delay is a random value in the interval _retryInterval * exponentialBase^(attempts)_ and _retryInterval * exponentialBase^(attempts+1)_.
The defaults were changed:
- retryInterval=5_000
- exponentialBase=2 (it is now also configurable)
- maxRetryDelay=125_000
- maxRetries=5
Retry delays are by default randomly distributed within the ranges of [5_000-10_000, 10_000-20_000, 20_000-40_000, 40_000-80_000, 80_000-125_000]. 
Added is also _MaxRetryTime_ option. When an overall time spent by retrying exceeds a maxRetryTime (180_000 millis by default), the write is not retried and fails.
=> feat: use exponential retry strategy

CHANGELOG.md, README.md, api/write.go, api/write_test.go, internal/write/queue.go, internal/write/queue_test.go, internal/write/service.go, internal/write/service_test.go
Added possibility for a user to control async failed writes by setting custom `WriteFailedCallback` to WriteAPI.
=> feat: adding WriteFailedCallback to let user control of failed writes

CHANGELOG.md, README.md, api/query_test.go, api/write_test.go, client.go, client_e2e_test.go, client_test.go, internal/write/service_test.go
Closes #284 
Improving server state functions:
- added Ping() - the only way how to check Cloud server state (**Client interface breaking change**)
- Health() and Ready() fails when connecting to Cloud
- Ready() returns server uptime info, instead of bool (**Compatibility Breaking Change** )
=> feat: server state check functions improvements

CHANGELOG.md, api/query/table.go, api/query/table_test.go, api/query_test.go
Closes #283
Added *FluxRecord.Result()* function as a convenient way to retrieve the Flux result name of data.
The `Result()` function extends collection of already existing accessor functions: `Table(), Start(), Stop(), Time(),  Measurement() and Value()`
=> feat: adding FluxRecord.Result() function

api/writeAPIBlocking.go
=> fix: retain full error information for blocking writes (#293)

api/writeAPIBlocking.go, api/writeAPIBlocking_test.go
This optimizes `WriteAPIBlocking.WriteRecord` in the case where a single string is provided, and explicitly documents that batches (records separated/terminated by newline) can be passed.  A test is added to confirm that this works as expected.
Unless the server chokes on empty lines this should resolve the need that motivated #295.
=> chore: optimize single-record blocking write

CHANGELOG.md, api/writeAPIBlocking.go, client_e2e_test.go, internal/test/generators.go, internal/test/http_service.go
- Final `WriteAPIBlocking.WriteRecord` optimization.
- Add ChangeLog entry for previous PRs
=> feat: further improve WriteAPIBlocking.WriteRecord

internal/write/service.go
Closes the response body after making a `WriteBatch` call. Failing to close the response body was keeping OpenCensus spans from being exported when using `ochttp.Transport` (see: https://github.com/census-instrumentation/opencensus-go/blob/49838f207d61097fc0ebb8aeef306913388376ca/plugin/ochttp/trace.go#L94)
=> fix: Close the response body of a WriteBatch call

CHANGELOG.md, api/query/table.go, api/query/table_test.go, api/query_test.go
Closes #301
- `FluxRecord.Table()` returns value of the `table` column.
- `FluxRecord.String()` returns values sorted  by key.
=> fix: FluxRecord.Table() returns value of the table column

api/query.go, api/query_test.go
| recently added an Influx Integration to another system and it was difficult to mock QueryTableResult so thought I'd make a PR to improve that.
QueryTableResult is a struct with private unexported fields, so
mocking this in external tests when the Influx client is used is
difficult. This adds an exported constructor to make external mocking
and testing easier.
=> test: add an exported constructor for QueryTableResult

.circleci/config.yml, CHANGELOG.md, README.md, api/examples_test.go, api/query.go, api/query_test.go, go.mod, go.sum
Added support for [Flux query parameters](https://docs.influxdata.com/influxdb/cloud/query-data/parameterized-queries/), available in InfluxDB Cloud only at this moment.
`QueryAPI` is extended with `QueryWithParams` and `QueryRawWithParams`.
Query parameters can be passed as a struct or map. Param values can be only simple types or `time.Time`.
The name of a struct field or a map key (must be a string) will become a param name
The name of the parameter represented by a struct field can be specified by JSON annotation:
```go
type Condition struct {
Start  time.Time  `json:"start"`
Field  string     `json:"field"`
Value  float64    `json:"value"`
}
```
Additionally, this requires changing the minimum Go version to 1.17.
Closes #146
=> feat: adding flux query parameters

.circleci/config.yml
The Codecov Bash Uploader is deprecated - https://docs.codecov.com/docs/about-the-codecov-bash-uploader. We have to switch to new one - https://docs.codecov.com/docs/codecov-uploader.
=> chore(ci): use new codecov uploader for reporting code coverage

CHANGELOG.md, client.go
Closes #312
Masking token in log.
=> fix: masking token for logging

CHANGELOG.md, api/write.go
This PR aims to address https://github.com/influxdata/influxdb-client-go/issues/317 . If multiple goroutines call `influxdb2.Client.Close()`, or `api.WriteAPI.Close()`, it is possible for there to be a panic due to closing a closed channel.
=> fix: add concurrency panic protection around Client and WriteAPIImpl Close

CHANGELOG.md, api/tasks.go, api/tasks_e2e_test.go
Closes #322
Added `TasksAPI.CreateTaskByFlux` to allow full control of the task script.
=> feat: Adding TasksAPI.CreateTaskByFlux

internal/write/service.go, internal/write/service_test.go
Fixes logic error in management of retry buffer that leads to deadlock scenario where write retries cease if server connection is lost for longer than MaxRetryTime
=> fix: write retry queue stops retrying

api/write_test.go, internal/write/service.go, internal/write/service_test.go
Fixes write and retry tests on Windows
=> fix(test): use higher timeouts on Windows

CHANGELOG.md, internal/write/service.go
Changing logging level of messages about discarding batch to Error. A part of the fix for #340
=> fix: logging messages about discarding batch as error

CHANGELOG.md, api/write.go, api/write_test.go, internal/test/http_service.go, internal/write/service.go, internal/write/service_test.go, log/logger.go
Closes #340
Added `internal/write/Service.Flush()` which instantaneously writes batches from the retry queue.
`WriteAPI.Flush()` also calls that.
=> fix: WriteAPI.Flush() also flushes retry queue

CHANGELOG.md, api/write/options.go, api/write/options_test.go, internal/write/service.go, internal/write/service_test.go
Added `write.Options.Consitency` parameter to support InfluxDB Enterprise.
=> feat: added consistency params support

CHANGELOG.md, internal/write/service.go, internal/write/service_test.go
Skip retrying on specific write errors (mostly partial write errors).
Inspired by [Telegraf's InfluxDB output](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/influxdb/http.go#L401)
=> fix: skip retrying on some errors

CHANGELOG.md, README.md, api/writeAPIBlocking.go, api/writeAPIBlocking_test.go, internal/test/http_service.go
Closes #336
Added support for implicit batching to `WriteAPIBlocking`. It's off by default, enabled by `EnableBatching()`.
=> feat: add implicit batching to writeAPIBlocking

CHANGELOG.md, api/write.go, api/writeAPIBlocking.go, internal/test/http_service.go
Closes #352 
More efficient synchronization around batching related code in WriteAPIBlocking
=> fix: efficient write blocking synchronization

api/writeAPIBlocking.go
Commit https://github.com/influxdata/influxdb-client-go/pull/350/commits/a9c1e378757965a5e5bc81b7b5a3f09cbbdeec97 introduced a bug, where a successful `Flush` returns a non-nil error because the internal function (`w.service.WriteBatch`) returns a concrete pointer and not an `error`.
Closes #360 
This bug is not present without Batching because the return value of `WriteBatch()` is properly checked before returning from the function `writeAPIBlocking.write()`. This code path is skipped by delegating the work to `writeAPIBlocking.flush()` instead.
```go
func (w *writeAPIBlocking) write(ctx context.Context, line string) error {
if atomic.LoadInt32(&w.batching) > 0 {
w.mu.Lock()
defer w.mu.Unlock()
w.batch = append(w.batch, line)
if len(w.batch) == int(w.writeOptions.BatchSize()) {
return …
```
=> fix(WriteAPIBlocking): properly return error from flush()

CHANGELOG.md, api/http/options.go, api/http/options_test.go, api/http/service.go, api/writeAPIBlocking.go, client.go, client_test.go, example_ua_set_test.go, internal/http/userAgent.go, options.go, options_test.go, version.go
Closes #356 
Added new option for setting the application name. Application name is then added to the end of Go client version string: E.g. `Influxdb-client-go/2.10.0 (linux; amd64) IoTHub/1.10`
- Added also example how to completely overwrite User-Agent header value using the Doer interface
=> feat: Allow setting of application name to the User-Agent header value

CHANGELOG.md, internal/write/service.go, internal/write/service_test.go
Closes #362 
Checking calculated numbers to avoid passing a negative number to the random generator.
=> fix: retry delay calculation check

CHANGELOG.md, api/http/options.go, api/http/options_test.go
Closes #367 
Added proxy to the client's custom HTTP transport.
=> fix: allowing proxy from environment

CHANGELOG.md, domain/client.gen.go, domain/templates/imports.tmpl, go.mod, go.sum
Signed-off-by: andig <cpuidle@gmx.de>
Remove deprecated pkg/errors. Depends on https://github.com/influxdata/influxdb-client-go/pull/387, needs rebase/tidy after https://github.com/influxdata/influxdb-client-go/pull/387 has been merged.
=> chore(deps): remove deprecated pkg/errors

.circleci/config.yml, CHANGELOG.md
Closes #
_ Update circleci machine image to ubuntu-2204:current, the current one is deprecated
_ Update circleci build go version to 1.22.2, go version < 1.22.2 will cause error
=> fix: update machine image ci

go.mod, go.sum
Update github.com/oapi-codegen/runtime from v1.0.0 to v1.1.1 to fix high severity vulnerabilities in the markdown package https://github.com/oapi-codegen/runtime/releases/tag/v1.1.1
=> chore: update github.com/oapi-codegen/runtime version

README.md
=> docs: update README.md about the code block
